### ISSUE TITLE
switch to the granite provided by rhel ai rather than huggingface

### ISSUE THREAD

**Issue by cooktheryan** [opendatahub-io/ilab-on-ocp#152]
`ilab model download --repository docker://registry.redhat.io/rhelai1/granite-7b-starter --release latest`

Transition the above command into the pipeline rather than using huggingface

**Comment by tumido** [comment]
Sadly `ilab model download` makes things only complicated:
- It requires `ilab config init` or a precreated config file - we can fake it but still - it's a nuisance
- If an OCI reference is used (which [has to be prefixed with `docker://` 🤦](https://github.com/instructlab/instructlab/blob/fa6073daf084f24346af05c021feb8f1eaa4cc44/src/instructlab/utils.py#L606)), all it does is to transform the `--repository`, `--release` and `--model-dir` args into [`skopeo copy {repository}@{release} oci:/{model-dir}` command](https://github.com/instructlab/instructlab/blob/fa6073daf084f24346af05c021feb8f1eaa4cc44/src/instructlab/model/download.py#L212-L217).

IMO it would be much better if we could use https://github.com/containers/ramalama or something instead of relying on this head-scratch logic by `ilab`...

**Comment by leseb** [comment]
@tumido, for a small clarification, the token is not needed if we download an image from the instructable repository. By the way, I'm curious how other projects handle the token.

**Comment by tumido** [comment]
Yeah, correct. However so far we've been using `ibm-granite/granite-7b-base` as the default base model. This model can be downloaded without auth, but not via `ilab model download` (as a workaround, setting `HF_TOKEN` to invalid, stub value, works just fine here).

**Comment by cooktheryan** [comment]
@tumido @MichaelClifford @sallyom based on the conversations yesterday it seems like we can be in line with phase 2 and grab the model from S3. This will require us to remove the hugging face model pull step and integrate with a the location in object storage

**Comment by leseb** [comment]
> @tumido @MichaelClifford @sallyom based on the conversations yesterday it seems like we can be in line with phase 2 and grab the model from S3. This will require us to remove the hugging face model pull step and integrate with a the location in object storage

That sounds great! An additional benefit to this is that we don't need to install `huggingface_hub` in the image anymore 🥳
